export enum Routes {
  ABOUT_US = "AboutUs",
  BASKET = "Basket",
  BOUGHTPAGE = "Bougth",
  COMPLETED_ORDER = "CompletedOrder",
  CONTACTS = "Contacts",
  FAVORITES = "Favorites",
  FORGET_PASSWORD = "ForgetPassword",
  HOME = "/",
  LOG_IN = "LogIn",
  NOT_FOUND = "NotFound",
  PAYMENT_AND_DEVELIVERY = "PaymentAndDevelivery",
  PLACINGORDER = "PlacingOrder",
  POLICY = "Policy",
  PROFILE = "Profile",
  SEARCH = "Search",
  SHOP = "Shop",
  SHOPNEW = "Shop",
  SING_IN = "SingIn",
  USER_ACCEPTED = "UserAccepted"
}
